spring.application.name=MockitoDepJPA

spring.datasource.url=jdbc:mysql://localhost:3306/webhook
spring.datasource.username=[INSIRA_SEU_NOME]
spring.datasource.password=[INSIRA_SUA_SENHA]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
